### ISSUE TITLE
[建议]提供绿色便携版

### ISSUE THREAD

**Issue by chenshaoju** [1357310795/MyComputerManager#1]
作者你好：

希望能提供免安装，绿色便携版的 MyComputerManager ，以便复制到U盘或者无法安装软件的环境。

感谢。

**Comment by 1357310795** [comment]
Releases提供的exe文件就是单文件绿色版，无需安装直接使用

**Comment by chenshaoju** [comment]
原来如此，因为习惯性右键用7zip解压，以为是安装程序。

感谢。

**Comment by 1357310795** [comment]
> 原来如此，因为习惯性右键用7zip解压，以为是安装程序。
> 
> 感谢。

hhh，只是用7zsfx打包成单文件了
