### ISSUE TITLE
win10打不开没反应

### ISSUE THREAD

**Issue by ShenLanD** [1357310795/MyComputerManager#10]
win10打不开光标转几圈就没了，用win11测能打开但是整个软件白蒙蒙的（net4.7.2已安装）

**Comment by 1357310795** [comment]
wpf-ui的问题，已经在反馈了
https://github.com/lepoco/wpfui/issues/275

**Comment by 1357310795** [comment]
> 软件白蒙蒙的
菜单栏还在吗？

**Comment by ShenLanD** [comment]
win11可以，忘了切换成暗色模式了

**Comment by 1357310795** [comment]
经过测试，只要切换一下系统主题色，就不会崩溃了
