### ISSUE TITLE
坚果云不能关闭

### ISSUE THREAD

**Issue by LarryKHite** [1357310795/MyComputerManager#11]
感谢，非常好用，就是坚果云不能关闭。
<img width="340" alt="2022-07-19_135118" src="https://user-images.githubusercontent.com/9220139/179675619-041ee1a8-97dd-4b0a-9019-9b5aa3d0cc60.png">

**Comment by 1357310795** [comment]
参考#8，对注册表HKLM的写入需要管理员权限。右键使用管理员权限打开程序。

**Comment by 1357310795** [comment]
为了遵守最小权限原则，程序并没有强制要求管理员权限
