### ISSUE TITLE
交大云盘图标无法删除

### ISSUE THREAD

**Issue by Bit-Part-Young** [1357310795/MyComputerManager#14]
如下图所示，请问有无解决方法呢？
![](https://s2.loli.net/2022/08/02/4LCIcBiHqPO3VoD.png)

**Comment by 1357310795** [comment]
参见#8
> 对注册表HKLM的写入需要管理员权限。右键使用管理员权限打开程序。

**Comment by Bit-Part-Young** [comment]
> 参见#8
> 
> > 对注册表HKLM的写入需要管理员权限。右键使用管理员权限打开程序。

已解决，十分感谢！
