### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by k650dg4d2** [1357310795/MyComputerManager#15]
希望侧栏的快速访问和3d对象，视频，图片什么的也可以去掉
![QQ截图20220808123000](https://user-images.githubusercontent.com/32454224/183339512-1d2984b2-3bfa-4cb8-a6b3-fe2b413e88bd.png)

**Comment by 1357310795** [comment]
请使用Dism++之类的软件

![image](https://user-images.githubusercontent.com/35869804/183356670-f6e8230c-0b5f-47d9-9d13-491be870192c.png)
