### ISSUE TITLE
重启电脑后得重新设置

### ISSUE THREAD

**Issue by gqyanann** [1357310795/MyComputerManager#16]

**Comment by 1357310795** [comment]
能否具体描述？重启后关掉的图标又出现了？

**Comment by gqyanann** [comment]
嗯，图标出现了，点开软件发现又生成了重复选项，OD和百度盘的图标

**Comment by 1357310795** [comment]
那就是软件又写回注册表了😂

这其实挺难办的。如果要修改注册表权限，会导致新安装的应用没法写入。

百度网盘的话，在设置里关吧……Onedrive参考[这里](http://www.nndssk.com/dngz/34166699BHx6.html)关闭

**Comment by gqyanann** [comment]
居然忘了百度直接有设置，谢谢

**Comment by Wrandz** [comment]
@1357310795 太棒了，这软件，我真真的受不了百度网盘那个百度同步盘在侧边栏的快捷方式，看着难受，这个软件完美的解决了！

**Comment by mengyuhanbing** [comment]
@1357310795 太感谢了，这软件，昨天我突然发现驱动器那里有个空白图标，太流氓了用你这个软件显示是驱动人生残留的，但是我点图标删除居然显示explorer.exe把我整了一下午并且去注册表NameSpace项目还没得这个空白图标的项，太流氓了，这个软件完美解决了
