### ISSUE TITLE
添加锁定功能

### ISSUE THREAD

**Issue by HaujetZhao** [1357310795/MyComputerManager#18]
通过编辑注册表权限，让流氓软件失去对 namespace 的写入能力。

实现可参见：[Protect-Windows-Context-Menu/02-保护Explorer盘符.bat](https://github.com/HaujetZhao/Protect-Windows-Context-Menu/blob/master/02-%E4%BF%9D%E6%8A%A4Explorer%E7%9B%98%E7%AC%A6.bat)

**Comment by 1357310795** [comment]
感谢建议，但是修改注册表权限可能导致意料之外的后果，不适合普通用户使用，故暂时不会加入MyComputerManager中

**Comment by HaujetZhao** [comment]
ok
