### ISSUE TITLE
小米wifi安装后的“云优盘”检测不到无法删除

### ISSUE THREAD

**Issue by star2k** [1357310795/MyComputerManager#2]
小米wifi安装后的“云优盘”检测不到无法删除
![Snipaste_2022-07-09_16-33-17](https://user-images.githubusercontent.com/9582078/178098400-a48f9546-f99f-41ef-a70d-ffa5b3fb0f5f.png)

**Comment by star2k** [comment]
[小米wifi_1b601_848.zip](https://github.com/1357310795/MyComputerManager/files/9076128/wifi_1b601_848.zip)

**Comment by 1357310795** [comment]
感谢反馈，初步判断是x86程序和x64程序注册表不相通的问题，可能需要一些时间来修复

**Comment by 1357310795** [comment]
> 感谢反馈，初步判断是x86程序和x64程序注册表不相通的问题，可能需要一些时间来修复

已解决，原来是MiWiFi把NameSpace的Key写在了HKCU下
```
计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{F5270E09-D417-4C5C-93BC-551E5F22ACA6}
```
却把CLSID的Key写在了HKLM下
```
计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{F5270E09-D417-4C5C-93BC-551E5F22ACA6}
```
这程序员肯定是网上瞎找的代码，看不懂直接用😅
