### ISSUE TITLE
功能需求：添加资源管理器左侧选项的编辑功能

### ISSUE THREAD

**Issue by No5972** [1357310795/MyComputerManager#23]
# 发现已经有人在 #6 提过了，抱歉，自己关闭了

---

我们已经在 #20 注意到了这个需求。不过还是希望新开一个 issue 详细说明一下这个问题。

刚刚在知乎发现了已经有人遇到了这个麻烦。一些第三方的应用软件在资源管理器的左侧添加了选项，但是一旦这个应用软件损坏，就会导致无法直接删除这个选项。

![](https://pic4.zhimg.com/v2-d41fa866bc010a45972e8e24462b481f_b.jpeg)

刚刚鄙人和同事在注册表编辑器里面找了一下，已经把这个配置找到了，这个“资源管理器左侧选项”的注册表位于

```
HKEY_CLASSES_ROOT\CLSID\{CLSID}
```

里面有一个 DWORD (32位) 值 ```System.IsPinnedToNameSpaceTree```，这个就是该 CLSID 对应的应用软件的“资源管理器左侧选项”的设置。设为 0 表示*不在*“资源管理器左侧选项”显示，设为 1 表示*在*“资源管理器左侧选项”显示。

相关资料：[到底怎么把这wps云盘图标弄走啊，右键也没有删除? - 知乎](https://www.zhihu.com/question/660627864/answer/3551339431)

希望作者考虑一下这个功能需求。谢谢。

**Comment by 1357310795** [comment]
为何关闭了呢？

**Comment by No5972** [comment]
> 为何关闭了呢？

@1357310795 刚刚发现之前有人提过这个需求了，在 #6

**Comment by 1357310795** [comment]
好，如果侧边栏管理功能无法使用，或者可以优化，可以再提出，看看有没有新的方案（）
