### ISSUE TITLE
可不可以增加添加文件夹快捷方式？

### ISSUE THREAD

**Issue by LeefenChen** [1357310795/MyComputerManager#4]
这么大一块地方增加几个常用文件夹快捷方式真是极好的。如果能放在磁盘分区后面那就更好了

**Comment by 1357310795** [comment]
![image](https://user-images.githubusercontent.com/35869804/178103875-53f1bdeb-6a90-4953-bf66-f3f967e4ffa1.png)
这个地方是可以带命令行参数的
比如我写
```
explorer C:\Users\Public\
```
![image](https://user-images.githubusercontent.com/35869804/178104133-f2e97977-b49f-4537-b819-5694c13384f2.png)

就能做到快捷方式。当然这样会打开新窗口，如果要在同一个窗口打开，估计得写个shell扩展的dll，就太麻烦了。
***
> 放在磁盘分区后面
win10推荐用OldNewExplorer，win11用[ExplorerPatcher](https://github.com/valinet/ExplorerPatcher)

**Comment by LeefenChen** [comment]
文件夹添加是可以，真好，多窗口不用担心，我用的Clover本来就是多选项卡。
不过刚才试了一下两个软件想把新增的文件夹放磁盘分区后面都没有实现的功能。小郁闷了

**Comment by 1357310795** [comment]
hh，我好像理解错了，要放在磁盘分区那个类里的后面啊，那就要用[Rclone](https://rclone.org/)了
![image](https://user-images.githubusercontent.com/35869804/178106603-046798f4-c183-46ef-b1fc-ba03afa95cd8.png)
![image](https://user-images.githubusercontent.com/35869804/178106581-f9f31af4-d78a-4315-95f1-97c2f91786d1.png)
![image](https://user-images.githubusercontent.com/35869804/178106588-bf11fb2d-067b-4495-b896-6ec6f823d9be.png)

**Comment by LeefenChen** [comment]
你的两个网盘有个其他分类，教教我怎么搞出这个其他也好，这比跟在分区后面分的更清楚

**Comment by 1357310795** [comment]
> 你的两个网盘有个其他分类，教教我怎么搞出这个其他也好，这比跟在分区后面分的更清楚

网上也能找到的
![image](https://user-images.githubusercontent.com/35869804/178108370-4b071074-3c2a-484e-92a5-bf89cca1c2aa.png)

**Comment by LeefenChen** [comment]
> > 你的两个网盘有个其他分类，教教我怎么搞出这个其他也好，这比跟在分区后面分的更清楚
> 
> 网上也能找到的 ![image](https://user-images.githubusercontent.com/35869804/178108370-4b071074-3c2a-484e-92a5-bf89cca1c2aa.png)

原来是这样，太赞了，再用你的软件可以在这个其他分类里添加好多常用文件夹。
不过一个新问题来了，能不能再搞个一键备份还原功能，做一次系统都没了重新添加一次怪麻烦的。

**Comment by 1357310795** [comment]
有考虑过增加导出`.reg`功能，不难实现，后续应该会加

**Comment by LeefenChen** [comment]
> 有考虑过增加导出`.reg`功能，不难实现，后续应该会加

好的，期待后续；
本来是做减法的软件，让我把加法给发扬光大了，哈哈，起大作用了，开心，感谢！
