### ISSUE TITLE
腾讯视频の快捷方式无法被识别出来

### ISSUE THREAD

**Issue by Hakuin123** [1357310795/MyComputerManager#5]
详见https://b23.tv/nNAsHRT
这个UP介绍了这款软件，不过也发现了一个小bug，rt
当然如果1.0.1版本修复了这个bug就当我没说
我电脑上没有腾讯视频，所以没有尝试
顺便，感谢大佬做的这个项目！

**Comment by Hakuin123** [comment]
另外，刚刚翻issue翻到这么一句话：
“初步判断是x86程序和x64程序注册表不相通的问题，可能需要一些时间来修复”
腾讯视频电脑版是32位程序，有没有可能是这个问题？

**Comment by Hakuin123** [comment]
再补一句，原视频下方有人给出，可以把注册表：
“计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace ”
设置为只读
建议考虑加上这个功能
（当然我知道这个不应该发在issue，只是为了话题连贯性，打扰请删）

**Comment by 1357310795** [comment]
腾讯视频的问题已确认，我在找它把Key藏哪了（

**Comment by 1357310795** [comment]
> 再补一句，原视频下方有人给出，可以把注册表： “计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace ” 设置为只读 建议考虑加上这个功能 （当然我知道这个不应该发在issue，只是为了话题连贯性，打扰请删）

我觉得意义不大，修改权限本身是比较危险的。大家也不会天天安装软件。出现一个图标就删/禁一个呗

**Comment by 1357310795** [comment]
> 再补一句，原视频下方有人给出，可以把注册表： “计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace ” 设置为只读 建议考虑加上这个功能 （当然我知道这个不应该发在issue，只是为了话题连贯性，打扰请删）

找到了，这次确实是32位程序的问题

**Comment by 1357310795** [comment]
v1.02已发
