### ISSUE TITLE
可不可以再增加侧边栏的删除？

### ISSUE THREAD

**Issue by channelvison** [1357310795/MyComputerManager#6]
以wps网盘为例，除了会在我的电脑下增加盘符，也会在侧边栏快速访问下面增加，拜托。

**Comment by 1357310795** [comment]
会加。开发这个软件的一大原因就是没有任何现成的工具可以管理这些“快捷方式”，侧边栏也是这样。

目前看到在侧边栏加“快捷方式”的只有百度网盘同步空间和WPS网盘，所以暂时没写。后面会加上的。

**Comment by cv0cv0** [comment]
> 

OneDrive怎么都删不掉。

**Comment by 1357310795** [comment]
使用最新版，Onedrive、WPS网盘、同步空间都可以识别到

**Comment by Bian-Sh** [comment]
大佬你好，请问怎么讲自己的程序像 wps 网盘一样融入到资源管理器的呢？

**Comment by 1357310795** [comment]
> 大佬你好，请问怎么讲自己的程序像 wps 网盘一样融入到资源管理器的呢？

去看看[官方文档](https://docs.microsoft.com/zh-cn/windows/win32/shell/shell-entry)或者百度搜一搜吧。这种底层的东西我也不会……
