### ISSUE TITLE
请教下UI问题

### ISSUE THREAD

**Issue by winnie2007** [1357310795/MyComputerManager#7]
您好，我非常喜欢您的软件中的UI，但我不会使用WPF，想请教您一下怎样在.NET Framework 4.7.2中使用WPF-UI
内否赐教，感激不尽，谢谢

**Comment by 1357310795** [comment]
WPF-UI只能用在WPF框架啊。你想用在哪？

**Comment by winnie2007** [comment]
.NET Framework 4.7.2，就是您用的那个，不过您是和WPF控件同时使用的吧
WPF-UI可以只在.NET Framework 里面使用吗

**Comment by winnie2007** [comment]
> WPF-UI只能用在WPF框架啊。你想用在哪？

.NET Framework 4.7.2，就是您用的那个，不过您是和WPF控件同时使用的吧
WPF-UI可以只在.NET Framework 里面使用吗

**Comment by 1357310795** [comment]
你是不是想说，winforms？

**Comment by winnie2007** [comment]
> 你是不是想说，winforms？

对对对，就是winforms

**Comment by 1357310795** [comment]
winforms当然用不了了，快去学WPF吧（x

**Comment by winnie2007** [comment]
哦，行吧，谢谢咯 : )
