### ISSUE TITLE
关闭icloud照片失败

### ISSUE THREAD

**Issue by song-zi** [1357310795/MyComputerManager#8]
![QQ截图20220717095722](https://user-images.githubusercontent.com/33717168/179380780-a28b273b-84d7-4c83-b442-7632f0c63e0f.jpg)
关闭icloud照片失败如图所示。

![QQ截图20220717095826](https://user-images.githubusercontent.com/33717168/179380787-a68a8c22-9bbb-4a26-b3c8-63631d263adb.jpg)

**Comment by 1357310795** [comment]
对注册表HKLM的写入需要管理员权限。右键使用管理员权限打开程序。

**Comment by song-zi** [comment]
解决了，果然是需要打开管理员权限。
