### ISSUE TITLE
希望添加功能：我的电脑下方的各种快捷方式删除 如 文档 图片 下载 等

### ISSUE THREAD

**Issue by MikuOhashii** [1357310795/MyComputerManager#9]
双击此电脑进入文件管理器后
在 <此电脑> 和 <本地磁盘C D F> 之间 的 快捷方式一堆 <如 文档 图片 下载 等> 没什么用，无法直接删除，只能通过注册表。
希望软件添加功能，快捷删除

Double-click this computer to enter the file manager
A bunch of shortcuts between <this computer> and <local disk CD F> <such as document picture download, etc.> are useless and cannot be deleted directly, only through the registry.
Hope the software adds functions and deletes them quickly

**Comment by 1357310795** [comment]
请使用Dism++，我不想重复造轮子。
Please use Dism++，I dont want to reinvent the wheel.

![image](https://user-images.githubusercontent.com/35869804/179384485-1259d416-adf6-4e9f-bea6-6c5fe315c79d.png)
